server:
    port: 8090
spring:
    application:
        name: consumer-service
    cloud:
        nacos:
            config:
                server-addr: localhost:8848
            discovery:
                server-addr: localhost:8848
        sentinel:
            transport:
                dashboard: localhost:8089
            web-context-unify: false
    config:
        import: nacos:nacos-config-example.properties?refresh=true
feign:
    httpclient:
        enabled: true
    sentinel:
        enabled: true