server:
    port: 8080
spring:
    application:
        name: provider-service
    cloud:
        nacos:
            discovery:
                server-addr: localhost:8848
        sentinel:
            transport:
                dashboard: localhost:8089
            web-context-unify: false